# Generated by Django 2.2.7 on 2019-11-12 04:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 12, 4, 1, 17, 82145, tzinfo=utc)),
        ),
    ]
