# Generated by Django 2.2.7 on 2019-11-13 02:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20191111_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrylookup',
            name='reps',
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 13, 2, 18, 3, 997365, tzinfo=utc)),
        ),
    ]
