# Generated by Django 2.2.7 on 2019-11-13 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20191112_2018'),
    ]

    operations = [
    	migrations.RenameModel('Entry', 'Workout'),
    	migrations.RenameModel('EntryLookup', 'Entry')
    ]
