# Generated by Django 2.2.7 on 2019-11-13 03:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20191112_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 13, 3, 16, 52, 266002, tzinfo=utc)),
        ),
    ]
